### ISSUE TITLE
Error following the README.md

### ISSUE THREAD

**Issue by numerized** [appodeal/appodeal-cordova-demo#1]
Hi mate, this trace is when installing last version on a fresh appodeal-cordova-demo project :

cordova plugin add /Users/numerized/Work/00_Github/appodeal-cordova-plugin :

Installing "com.appodeal.plugin" for ios
Error during processing of action! Attempting to revert...
Failed to install 'com.appodeal.plugin':CordovaError: Uh oh!
"/Users/numerized/Work/00_Github/appodeal-cordova-demo/plugins/com.appodeal.plugin/libs/appodeal-ios-sdk-mobile-adapters/APDAdColonyAdapter.embeddedframework/libAPDAdColonyAdapter.a" not found!
    at copyFile (/Users/numerized/Work/00_Github/appodeal-cordova-demo/platforms/ios/cordova/lib/plugman/pluginHandlers.js:274:36)
    at copyNewFile (/Users/numerized/Work/00_Github/appodeal-cordova-demo/platforms/ios/cordova/lib/plugman/pluginHandlers.js:306:5)
    at installHelper (/Users/numerized/Work/00_Github/appodeal-cordova-demo/platforms/ios/cordova/lib/plugman/pluginHandlers.js:224:13)
    at handlers.source-file.install (/Users/numerized/Work/00_Github/appodeal-cordova-demo/platforms/ios/cordova/lib/plugman/pluginHandlers.js:34:13)
    at Object.ActionStack.process (/Users/numerized/Work/00_Github/appodeal-cordova-demo/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/UseError: Uh oh!
"/Users/numerized/Work/00_Github/appodeal-cordova-demo/plugins/com.appodeal.plugin/libs/appodeal-ios-sdk-mobile-adapters/APDAdColonyAdapter.embeddedframework/libAPDAdColonyAdapter.a" not found!

**Comment by numerized** [comment]
my bad I unzipped in a subfolder of libs
